[wip] feat: Replace $sum with the column sum
weseek/growi-plugin-datatables pull request #3
Opened 2024-01-07 08:41 UTC by miya

2024-01-07 10:11 UTC, miya commented on src/DataTable.tsx
> +        const sum = (api.column(column).data() as any).sum();
https://datatables.net/plug-ins/api/sum() を参考にしました

2024-01-07 10:11 UTC, miya commented on src/DataTable.tsx
> +    }
CalcMethod が含まれている cell の row と column を取得するメソッド

2024-01-07 10:58 UTC, ryu-sato requested changes

2024-01-07 10:58 UTC, ryu-sato commented on src/DataTable.tsx
> +      // テーブル中に存在する {sum} をそのカラムの合計値に置き換える
CalcMethod の一部として sum を定義したのは、今後 avg などを実装するときに変更点が少なく済むので良い考えだと思います。

今は avg を追加しようとした場合、以下のような変更が必要になり、ほぼ同じロジックを追加することになると思うので、CalcMethod に計算ロジックも所有させてもう少し汎用的にしましょう。

```js
const calcMethodPosition = findCalcMethodPosition(api, CalcMethod.avg);
calcMethodPosition.forEach((pos) => {
    const { row, column } = pos;
    const sum = (api.column(column).data() as any).avg();
    api.cell({ row, column }).data(sum);
}
```

CalcMethod の定義を変更するだけで sum 以外の計算ができるようになると理想的だと思います。

```js
export const CalcMethod = {
  sum: {
    replaceValue: '{sum}',
    calcMethod: () => { ... },
  },
  avg: {
    ...
  }
};
```

2024-01-07 10:58 UTC, ryu-sato commented on src/DataTable.tsx
> +        const { row, column } = pos;
好みが分かれるところだと思いますが、 `pos` 自体を使わないのであれば `({ row, column }) => ...` としてよいと思います。
なるべく使わない変数は定義しない方が個人的には好みです。（`sum` のような計算結果に名前を付けたい場合など、分かりやすくする場合を除く）

2024-01-07 10:58 UTC, ryu-sato commented on src/DataTable.tsx
> +        const sum = (api.column(column).data() as any).sum();
この column には `sum` 関数で置き換えられた値が入る可能性があると思うので、「`{sum}` などの計算式が書かれたセル**以外**」をうまく対象にするようにしてみてください。

おそらくですが、以下のような table の場合に合計値が重複してしまうのではないかと思います。

```md
| A |
| --- |
| {sum} |
| 1 |
| 2 |
| 3 | 
| {sum} |
```

↓

```
| A |
| --- |
| 6 |
| 1 |
| 2 |
| 3 | 
| 12 | <= おそらく先に `sum` を計算した結果の値を含めて合計してしまう
```

2024-01-07 10:58 UTC, ryu-sato commented on src/DataTable.tsx
> +    const findCalcMethodPosition = (api: DataTableApi<any>, method: CalcMethod): Array<{row: number, column: number}> => {
js の配列操作において（ほかの言語でも）、find～ は1つの場所を返すメソッドに使うと思うのと、戻り値は複数の position になると思うので、`getEveryCalcMethodPositions` などの方が適切だと思います。

2024-01-07 10:58 UTC, ryu-sato commented on src/DataTable.tsx
> +      const pos = []
複数の position が入るので `poss` または `posArr` の方がよいでしょう。

2024-01-07 11:42 UTC, miya commented on src/DataTable.tsx
> +        const sum = (api.column(column).data() as any).sum();
> おそらくですが、以下のような table の場合に合計値が重複してしまうのではないかと思います。
確かに再現しました。ご指摘ありがとうございます。計算処理と置き換え処理を分けて対処しました。

2024-01-07 11:43 UTC, miya commented on src/DataTable.tsx
> +    const findCalcMethodPosition = (api: DataTableApi<any>, method: CalcMethod): Array<{row: number, column: number}> => {
getEveryCalcMethodData に修正しました。(calcMethod も返すように修正したため)

2024-01-07 11:43 UTC, miya commented on src/DataTable.tsx
> +        const { row, column } = pos;
修正しました

2024-01-07 11:44 UTC, miya commented on src/DataTable.tsx
> +      // テーブル中に存在する {sum} をそのカラムの合計値に置き換える
interface が膨らむのは個人的に好みではなかったため、calc メソッドを新設し switch の中に処理を書くようにしました。

2024-01-07 11:45 UTC, miya commented on src/DataTable.tsx
> +      const pos = []
pos 変数をそのものを削除したため未対応

2024-01-07 16:54 UTC, miya commented on src/DataTable.tsx
> +      // テーブル中に存在する {sum} をそのカラムの合計値に置き換える
配列の方が使い勝手が良かったため以下のように修正しました。CalcMethod に必要なプロパティが揃っているオブジェクトを追加するだけで良いような機構にしています。

```typescript
const CalcMethod = [
  {
    methodType: '{sum}',
    calcMethod: (api: DataTableApi<any>, column: number): number => {
      return (api.column(column).data() as any).sum();
    },
  },
  {
    methodType: '{avg}',
    calcMethod: (api: DataTableApi<any>, column: number): number => {
      const sum = (api.column(column).data() as any).sum();
      const columnLength = api.column(column).data().length;
      return sum / columnLength;
    },
  },
] as const;
```

2024-01-08 05:18 UTC, ryu-sato requested changes

2024-01-08 05:18 UTC, ryu-sato commented on src/DataTable.tsx
> +    methodType: '{sum}',
縦(column)の sum を求めるので methodType は `vsum` にしておいてもらえますか？

もし横(row) の sum を求める関数が欲しくなったたときに `hsum` のように区別ができればプラグインとしての breaking changes にならずに済むので。

2024-01-08 05:18 UTC, ryu-sato commented on src/DataTable.tsx
> +    methodType: '{avg}',
こちらも `vavg` にしておいてください。

2024-01-08 05:18 UTC, ryu-sato commented
以下を対応したらマージしてください。

https://github.com/weseek/growi-plugin-datatables/pull/3#discussion_r1444178022
https://github.com/weseek/growi-plugin-datatables/pull/3#discussion_r1444178122

2024-01-08 05:25 UTC, ryu-sato commented on src/DataTable.tsx
> +    methodType: '{sum}',
`csum` (column sum) や `rsum` (row sum) にしても大丈夫です。

2024-01-08 06:25 UTC, miya commented on src/DataTable.tsx
> +    methodType: '{sum}',
`vsum` に修正しました

2024-01-08 06:25 UTC, miya commented on src/DataTable.tsx
> +    methodType: '{avg}',
`vavg` に修正しました

2024-01-08 06:25 UTC, merged